class APIError extends Error{
    constructor(
        statuscode,   //The HTTP status code representing the error (e.g., 400 for Bad Request, 404 for Not Found, 500 for Internal Server Error).
        message= "Something is wrong",
        errors= [],
        stack= ""     //"stack" refers to the Stack Trace—a detailed diagnostic list generated by Node.js or the browser whenever an error occurs.
    ){
        super(message)   //Calls the parent Error class constructor with the error message. This sets up the native error messaging behavior inside Node.js.
        this.statuscode = statuscode
        this.data = null
        this.message = message
        this.succuss = false
        this.errors  = errors

        if(stack){
            this.stack = stack;
        } else {
            Error.captureStackTrace(this, this.constructor);
        }
    }
}

export { APIError }